set shell=/bin/bash

set nocompatible             " Be iMproved, required.
filetype off                 " Required.

" Set the runtime path to include vundle and initialize.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'flazz/vim-colorschemes'

" All of your Plugins must be added before the following line
call vundle#end()            " Required.
filetype plugin indent on    " Required.

syntax enable		         " Enable syntax processing.
set tabstop=4       	     " Number of visual spaces per TAB.
set softtabstop=4   	     " Number of spaces in tab when editing.
set expandtab       	     " Tabs are spaces.
set number                   " Show line numbers.
set wildmenu                 " Visual autocomplete for command menu.
set showmatch                " Highlight matching [{()}].
set autoindent               " Automatically indent things.

" Move vertically by visual line.
nnoremap j gj
nnoremap k gk

" jk is escape.
inoremap jk <esc>

set textwidth=120

colorscheme colorsbox-stblue

" Delete trailing whitespace.
fun! <SID>StripTrailingWhitespace()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun

augroup whitespace
  autocmd!
  autocmd BufWritePre * :call <SID>StripTrailingWhitespace()
augroup END

nnoremap <leader>sv :source $MYVIMRC<CR>
