# Shell configuration.
# export MY_NAME=v
# export COMPUTER_NAME=local

# oh-my-zsh config.
plugins=(git zsh-autosuggestions)
ZSH_THEME="fishier"
export ZSH=/Users/$USER/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Enable direnv.
eval "$(direnv hook zsh)"
