# oh-my-zsh config.
export ZSH=/Users/$USER/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

ZSH_THEME="fishier"

plugins=(git zsh-autosuggestions)

# Shell configuration.
# export MY_NAME=v
# export COMPUTER_NAME=local

# enable direnv.
eval "$(direnv hook zsh)"
